# Generated by Django 5.1 on 2024-08-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosSensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.FloatField()),
                ('teor_gordura', models.FloatField()),
                ('ph', models.FloatField()),
                ('data_coleta', models.DateField()),
                ('hora_coleta', models.TimeField()),
                ('informacoes_adicionais', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
