# Generated by Django 5.1 on 2024-08-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadossensor',
            name='data_coleta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dadossensor',
            name='hora_coleta',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dadossensor',
            name='ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dadossensor',
            name='temperatura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dadossensor',
            name='teor_gordura',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
